include $(CARMEN_HOME)/src/Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += -lglv -lglobal -lz -lglut -lGLU -L/usr/X11R6/lib -lX11 \
	-lXext -lXi -lXmu

MODULE_NAME = "GLVIEW"

SOURCES =

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = glview

TARGETS = glview

glview:		glview.o

include $(CARMEN_HOME)/src/Makefile.rules
