include $(CARMEN_HOME)/src/Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += -lglv -lglobal -lipc -lz

MODULE_NAME = "GLV2VRML"

SOURCES =

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = glv2vrml

TARGETS = glv2vrml

glv2vrml:	vrmlout.o glv2vrml.o

include $(CARMEN_HOME)/src/Makefile.rules
