include $(CARMEN_HOME)/src/Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = "GLV"

SOURCES =

PUBLIC_INCLUDES = glv.h my_stdio.h
PUBLIC_LIBRARIES = libglv.a
PUBLIC_BINARIES =

TARGETS = libglv.a

libglv.a:	my_stdio.o glv.o

include $(CARMEN_HOME)/src/Makefile.rules
